version: "1.0.0"

services:
  backend:
    build: .
    container_name: apexlab
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - api-network
    depends_on:
      - db
    ports:
      - '$PORT:$PORT'
  db:
    image: postgres
    volumes:
      - pgData:/data/db
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - '$DB_PORT:$DB_PORT'
    networks:
      - api-network
  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - api-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
   pgData:

networks:
  api-network:
    driver: bridge

